# 向量化练习,计算向量x1、x2的内积、外积

In [2]:
import numpy as np
import time

In [3]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

# 数组、矩阵类型及区别
print("x1:")
print(x1)
print(np.shape(x1))
print(type(x1))
print("\nx11:")
x11=np.array(x1)
print(x11)
print(x11.shape)
print(type(x11))
print(x11.ndim)
print("\nx12 reshape:")
x12=x11.reshape(1,-1)
print(x12)
print(x12.shape)
print(type(x12))
print(x12.ndim)

x1:
[9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
(15,)
<class 'list'>

x11:
[9 2 5 0 0 7 5 0 0 0 9 2 5 0 0]
(15,)
<class 'numpy.ndarray'>
1

x12 reshape:
[[9 2 5 0 0 7 5 0 0 0 9 2 5 0 0]]
(1, 15)
<class 'numpy.ndarray'>
2


In [26]:
#求长度 len,size,shape
print("x1: "+str(len(x1)))
print("x11: "+str(len(x11)))
print("x11 shape: " + str(x11.shape[0]))
print("x12: "+str(len(x12)))

x1: 15
x11: 15
x11 shape: 15
x12: 1


In [38]:
#内积（dot product） 经典
tic = time.process_time()
dot = 0

for i in range(len(x1)):
    dot += x1[i]*x2[i]
    
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

#向量化
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.16205299999949574ms
dot = 278
 ----- Computation time = 0.09727000000037123ms


In [40]:
#外积 （outer product）
tic = time.process_time()
outer = np.zeros((len(x1),len(x2)))

for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j]=x1[i]*x2[j]

toc = time.process_time()
print ("outer = " +str(outer)+ "\n ---- Computation time = " +str(1000*(toc-tic))+"ms")


#向量化
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
 ---- Computation time = 0.4542890000003297ms


In [41]:
#对元素操作 （elementwise）
tic = time.process_time()
assert len(x1)==len(x2)
elewise = np.zeros(len(x1))
for i in range(len(x1)):
    elewise[i] = x1[i]*x2[i]

toc = time.process_time()
print ("elementwise = " + str(elewise)+ "\n ---- Computation time = " +str(1000*(toc-tic))+"ms" )

#向量化
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

elementwise = [81.  4. 10.  0.  0. 63. 10.  0.  0.  0. 81.  4. 25.  0.  0.]
 ---- Computation time = 0.1892999999997258ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.10311399999984872ms


In [43]:
#内积（矩阵）
tic = time.process_time()
w = np.random.rand(3,len(x1))
print(w)
gdot = np.zeros(w.shape[0]) #C模式：shape[0]为矩阵列数
for i in range(w.shape[0]):
    for j in range(len(x1)):
        gdot[i] += w[i,j]*x1[j]
        
toc = time.process_time()
print ("gdot = " + str(gdot)+ "\n ---- Computation time = " +str(1000*(toc-tic))+"ms" )

#向量化
tic = time.process_time()
mul = np.dot(w,x1)
toc = time.process_time()
print ("gdot = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

mul2 = np.dot(x1,w) ##this is wrong
print(mul2)

[[0.06004298 0.83993651 0.40698291 0.66569218 0.59285938 0.86967973
  0.34878008 0.08422812 0.22085165 0.51143498 0.17592105 0.16514098
  0.77918754 0.99555384 0.04399052]
 [0.1503287  0.88737274 0.33574334 0.53937347 0.45184042 0.55846776
  0.07074733 0.86777381 0.77254608 0.00963446 0.57935333 0.73791058
  0.58208285 0.72448604 0.69530792]
 [0.00731933 0.90240049 0.96048226 0.46743788 0.67284457 0.32052435
  0.46269867 0.15767594 0.12534812 0.49992348 0.42955622 0.50393579
  0.25538014 0.98876806 0.44303198]]
gdot = [17.89634196 18.66984687 17.38102823]
 ---- Computation time = 2.0885010000002424ms
gdot = [17.89634196 18.66984687 17.38102823]
 ----- Computation time = 0.10567799999972038ms


ValueError: shapes (15,) and (3,15) not aligned: 15 (dim 0) != 3 (dim 0)

# logistic梯度下降用到的函数

In [47]:
#损失函数

def L1(yhat,y):
    loss = np.sum(np.abs(yhat-y))
    return loss

def L2(yhat,y):
    loss = np.dot(yhat-y,(yhat-y).T)
    return loss

In [48]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L1 = 1.1
L2 = 0.43
